CredentialSchema:
  newrelic:
    app_id:
      type: string
      description: Your app id to connect to the NewRelic API with
    api_key:
      type: string
      description: Your api key to connect to the NewRelic API with
Cache:
  newrelic: Symfony\Component\Cache\Adapter\FilesystemAdapter
